
spring:
  application:
    name: mybatis-plus-code-generator
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

logging:
  level:
#    root: debug
    com.fengwenyi: debug
    com.baomidou: debug
server:
  port: 8000

custom:
  outdir: '/home/MyBatisGenerator/javaClass' #代码生成地址
  downloaddir: '/home/MyBatisGenerator/downZip' #代码下载地址
